name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.todayscoding }}
          TIMEZONE: Asia/Seoul
